name: Run Linter

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Install modules
      working-directory: ./client
      working-directory: ./server
      run: npm ci
    - name: Install eslint
      working-directory: ./client
      working-directory: ./server
      run: yarn add eslint
    - name: Run ESLint
      working-directory: ./client
      working-directory: ./server
      run: npx eslint ./client/**/*.{js,ts,tsx} ./server/**/*.{js,ts} --no-error-on-unmatched-pattern